sudo: required
language: csharp
mono: none
solution: Cupertino.sln
dotnet: 2.2
dist: xenial
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/Cupertino.Services.Tests/Cupertino.Services.Tests.csproj